version: '3.8'

services:
  mcpo-armis:
    build: .
    container_name: mcpo-armis
    ports:
      - "0.0.0.0:8100:8000"  # Expose on all interfaces, port 8100
    command: ["--config", "/config.json", "--port", "8000"]
    restart: unless-stopped
    environment:
      - DUMMY=value  # Keep environment section valid
      # Uncomment to use a specific token instead of generating one:
      # - MCPO_BEARER_TOKEN=your-custom-token-here
