#!/bin/bash
echo "=============================================="
echo "🔐 Current MCPO Configuration for OpenWebUI"
echo "=============================================="
echo ""
TOKEN=$(docker logs mcpo-armis 2>&1 | grep "Token:" | head -1 | awk -F': ' '{print $2}')
echo "Configuration for OpenWebUI:"
echo ""
echo "1. OpenAPI URL (use this exact URL):"
echo "   http://localhost:8100/armis-security/openapi.json"
echo ""
echo "2. Authentication:"
echo "   - Type: Bearer"  
echo "   - Token: $TOKEN"
echo ""
echo "=============================================="
echo "Test Command:"
echo "curl -H \"Authorization: Bearer $TOKEN\" \\"
echo "  http://localhost:8100/armis-security/openapi.json | jq .info"
echo "=============================================="
